=== e-vrvr/intervals/target/classes/schema/request.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           targetNamespace="com.intervals"
           xmlns="com.intervals"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="intervals_request">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="attendees">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="id" maxOccurs="unbounded" minOccurs="1"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="meeting_duration_minutes">
                    <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:minExclusive value="0"/>
                            <xs:maxExclusive value="600"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="timeslots_needed" default="1">
                    <xs:simpleType>
                        <xs:restriction base="xs:byte">
                            <xs:minExclusive value="0"/>
                            <xs:maxExclusive value="20"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="seeking_range">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:dateTime" name="from"/>
                            <xs:element type="xs:dateTime" name="to"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== e-vrvr/intervals/example/request.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<i:intervals_request xmlns:i="com.intervals"
                       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                       xsi:schemaLocation="com.intervals ../schema/request.xsd">
    <i:attendees>
        <i:id>Jack Slater</i:id>
        <i:id>Emil Rottmayer</i:id>
    </i:attendees>
    <i:meeting_duration_minutes>90</i:meeting_duration_minutes>
    <i:timeslots_needed>2</i:timeslots_needed>
    <i:seeking_range>
        <i:from>2015-11-03T13:00:00</i:from>
        <i:to>2015-11-03T15:00:00</i:to>
        <!-- timezone in terms of UTC time offset, for example -08:00 for PST, or +05:45 for Nepal time -->
        <i:timezone>+00:00</i:timezone>
    </i:seeking_range>
</i:intervals_request>
