=== e-vrvr/intervals/src/main/resources/schema/data.xsd
<xs:schema attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="com.intervals"
           xmlns="com.intervals">
    <xs:element name="intervals_data">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="data">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="entry" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:byte" name="id"/>
                                        <xs:element type="xs:string" name="name"/>
                                        <xs:element name="timezone" default="+00:00">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[+|-]+([0-1][0-3])[:]([0,3,4][0,5])"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="busy_time">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="entry" minOccurs="1" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element type="xs:date" name="date"/>
                                                                <xs:element ref="time_entries"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="time_entries">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="entry" minOccurs="1" maxOccurs="5">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:time" name="from"/>
                            <xs:element type="xs:time" name="to"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== e-vrvr/intervals/src/main/resources/data/data.xml
<?xml version="1.0" encoding="utf-8"?>
<i:intervals_data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xmlns:i="com.intervals"
                  xsi:schemaLocation="com.intervals ../schema/data.xsd">
    <i:data>
        <i:entry>
            <i:id>1</i:id>
            <i:name>Jack Slater</i:name>
            <i:timezone>+00:00</i:timezone>
            <i:busy_time>
                <i:entry>
                    <i:date>2015-11-02</i:date>
                    <i:time_entries>
                        <i:entry>
                            <i:from>10:00:00</i:from>
                            <i:to>11:00:00</i:to>
                        </i:entry>
                        <i:entry>
                            <i:from>15:00:00</i:from>
                            <i:to>17:30:00</i:to>
                        </i:entry>
                    </i:time_entries>
                </i:entry>
            </i:busy_time>
        </i:entry>
        <i:entry>
            <i:id>2</i:id>
            <i:name>Harry Tasker</i:name>
            <i:timezone>+01:00</i:timezone>
            <i:busy_time>
                <i:entry>
                    <i:date>2015-11-02</i:date>
                    <i:time_entries>
                        <i:entry>
                            <i:from>09:00:00</i:from>
                            <i:to>12:00:00</i:to>
                        </i:entry>
                        <i:entry>
                            <i:from>14:00:00</i:from>
                            <i:to>17:00:00</i:to>
                        </i:entry>
                    </i:time_entries>
                </i:entry>
            </i:busy_time>
        </i:entry>
        <i:entry>
            <i:id>3</i:id>
            <i:name>Emil Rottmayer</i:name>
            <i:timezone>+01:00</i:timezone>
            <i:busy_time>
                <i:entry>
                    <i:date>2015-11-02</i:date>
                    <i:time_entries>
                        <i:entry>
                            <i:from>10:00:00</i:from>
                            <i:to>13:00:00</i:to>
                        </i:entry>
                        <i:entry>
                            <i:from>15:00:00</i:from>
                            <i:to>16:00:00</i:to>
                        </i:entry>
                    </i:time_entries>
                </i:entry>
                <i:entry>
                    <i:date>2015-11-03</i:date>
                    <i:time_entries>
                        <i:entry>
                            <i:from>08:00:00</i:from>
                            <i:to>13:00:00</i:to>
                        </i:entry>
                        <i:entry>
                            <i:from>17:00:00</i:from>
                            <i:to>18:00:00</i:to>
                        </i:entry>
                    </i:time_entries>
                </i:entry>
            </i:busy_time>
        </i:entry>
        <i:entry>
            <i:id>4</i:id>
            <i:name>John Kimble</i:name>
            <i:timezone>+01:00</i:timezone>
            <i:busy_time>
                <i:entry>
                    <i:date>2015-11-02</i:date>
                    <i:time_entries>
                        <i:entry>
                            <i:from>10:00:00</i:from>
                            <i:to>13:00:00</i:to>
                        </i:entry>
                        <i:entry>
                            <i:from>15:00:00</i:from>
                            <i:to>16:00:00</i:to>
                        </i:entry>
                    </i:time_entries>
                </i:entry>
                <i:entry>
                    <i:date>2015-11-04</i:date>
                    <i:time_entries>
                        <i:entry>
                            <i:from>08:00:00</i:from>
                            <i:to>13:00:00</i:to>
                        </i:entry>
                        <i:entry>
                            <i:from>17:00:00</i:from>
                            <i:to>18:00:00</i:to>
                        </i:entry>
                    </i:time_entries>
                </i:entry>
            </i:busy_time>
        </i:entry>
    </i:data>
</i:intervals_data>
